import Note from "../../models/note.model.js";
import User from "../../models/user.model.js";
import Subject from "../../models/subject.model.js";
import uploadToCloudinary from "../../services/cloudinary.service.js";
import upload from "../middlewares/upload.middleware.js";
import asyncHandler from "../../utils/asyncHandler.js";
import apiError from "../../utils/apiError.js";
import apiResponse from "../../utils/apiResponse.js";
import { AuthRequest } from "../middlewares/auth.middleware.js";
import { Response } from "express";
import parseAIResponse from "../../utils/parseAIResponse.js";
import { analyzeLectureImage } from "../../services/ai/ai.service.js";
import { getPagination } from "../../utils/pagination.js";
import { noteQueue } from "../../jobs/queues/note.queue.js";

export const uploadNoteImage = asyncHandler(
  async (req: AuthRequest, res: Response) => {
    if (!req.file) {
      throw new apiError(400, "Image is required");
    }

    const imageUrl = await uploadToCloudinary(req.file.buffer);

    const note = await Note.create({
      userId: req.user!._id,
      imageUrl,
      status: "queued",
      mimeType: req.file.mimetype,
    });

    const job = await noteQueue.add(
      "process-note",
      {
        noteId: note._id,
        imageUrl,
      },
      {
        removeOnComplete: true,
        removeOnFail: 20,
      },
    );

    res
      .status(201)
      .json(new apiResponse(true, "Note queued for processing", { note }));

    // res.status(201).json(
    //   new apiResponse(true, 'Processing started', {
    //     noteId: note._id,
    //   })
    // )
    // try {
    //   const aiRawResponse = await analyzeLectureImage(
    //     req.file.buffer,
    //     req.file.mimetype
    //   )

    //   const aiData = parseAIResponse(aiRawResponse)
    //   const normalizedSubject=aiData.Subject.trim().toLowerCase()
    //   let subject = await Subject.findOne({
    //     userId: req.user!._id,
    //     title: {
    //         $regex:new RegExp(
    //             `^${normalizedSubject}$`,"i"
    //         )
    //     },
    //   })

    //   if (!subject) {
    //     subject = await Subject.create({
    //       userId: req.user!._id,
    //       title: aiData.subject,
    //       isAutoGenerated: true,
    //     })
    //   }

    //   note.subjectId = subject._id
    //   note.title = aiData.topic
    //   note.detectedSubject = aiData.subject

    //   note.aiContent = aiData.notes

    //   note.status = 'completed'
    // } catch (error) {
    //   note.status = 'failed'
    // }

    // await note.save()
  },
);

export const getNotesBySubjects = asyncHandler(
  async (req: AuthRequest, res: Response) => {
    const { subjectId } = req.params;
    const page = Number(req.query.page) || 1;
    const limit = Number(req.query.limit) || 10;
    const { skip } = getPagination(page, limit);
    const notes = await Note.find({ userId: req.user!._id, subjectId })
      .sort({ createdBy: -1 })
      .skip(skip)
      .limit(limit)
      .lean()
      .populate("subjectId", "title");
    res
      .status(200)
      .json(new apiResponse(true, "Notes fetched successfully", notes));
    return;
  },
);

export const getSingleNote = asyncHandler(
  async (req: AuthRequest, res: Response) => {
    const note = await Note.findOne({
      _id: req.params.id,
      userId: req.user!._id,
    });

    if (!note) {
      throw new apiError(404, "Note not found");
    }
    res
      .status(200)
      .json(new apiResponse(true, "Note fetched successfully", note));
    return;
  },
);

export const editNote = asyncHandler(
  async (req: AuthRequest, res: Response) => {
    const note = await Note.findOne({
      _id: req.params.noteId,
      userId: req.user!._id,
    });

    if (!note) {
      throw new apiError(404, "Note not found");
    }

    note.editedContent = req.body.editedContent;
    note.isEdited = true;
    await note.save();

    res
      .status(200)
      .json(new apiResponse(true, "Note updated successfully", note));
    return;
  },
);

export const deleteNote = asyncHandler(
  async (req: AuthRequest, res: Response) => {
    const note = await Note.findOneAndDelete({
      _id: req.params.noteId,
      userId: req.user!._id,
    });
    if (!note) {
      throw new apiError(404, "Note not found");
    }
    res
      .status(200)
      .json(new apiResponse(true, "Note deleted successfully", note));
    return;
  },
);

export const moveNote = asyncHandler(
  async (req: AuthRequest, res: Response) => {
    const note = await Note.findOne({
      _id: req.params.noteId,
      userId: req.user!._id,
    });
    if (!note) {
      throw new apiError(404, "Note not found");
    }
    note.subjectId = req.body.subjectId;
    await note.save();
    res
      .status(200)
      .json(new apiResponse(true, "Note moved successfully", note));
    return;
  },
);

export const getNoteStatus = asyncHandler(
  async (req: AuthRequest, res: Response) => {
    const note = await Note.findOne({
      userId: req.user?._id,
      _id: req.params.noteId,
    }).select(
      "status title detectedSubject errorMessage processingStartedAt processingCompletedAt subjectId",
    );
    if (!note) {
      throw new apiError(404, "Note note found");
    }
    res.status(200).json(new apiResponse(true, "Status fetched", note));
    return;
  },
);

export const searchNotes = asyncHandler(
  async (req: AuthRequest, res: Response) => {
    const q = req.query.q as string;
    if (!q.trim()) {
      throw new apiError(400, "Search query is required");
    }
    const notes = await Note.find({
      userId: req.user!._id,
      $or: [
        {
          title: {
            $regex: q,
            $options: "i",
          },
        },
        {
          aiContent: {
            $regex: q,
            $options: "i",
          },
        },
      ],
    })
      .populate("subjectId", "title")
      .sort({ createdAt: -1 });

    res
      .status(200)
      .json(new apiResponse(true, "Notes fetched successfully", notes));
  },
);

export const retryNoteAI = asyncHandler(
  async (req: AuthRequest, res: Response) => {
    const note = await Note.findOne({
      userId: req.user!._id,
      _id: req.params.noteId,
    });
    if (!note) {
      throw new apiError(404, "Note not found");
    }
    if (note.status !== "failed") {
      throw new apiError(400, "Only failed notes can be retried");
    }
    note.status = "processing";
    await note.save();
    res
      .status(200)
      .json(new apiResponse(true, "Retry started", { noteId: note._id }));
  },
);
