"use client"

import {
  Folder,
  MoreHorizontal,
  Share,
  Trash2,
  type LucideIcon,
} from "lucide-react"
import { NavLink } from "react-router-dom"

import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import {
  SidebarGroup,
  SidebarGroupLabel,
  SidebarMenu,
  SidebarMenuAction,
  SidebarMenuButton,
  SidebarMenuItem,
  useSidebar,
} from "@/components/ui/sidebar"
import { useLocation, Link } from "react-router-dom"
import { apiFetch } from "@/api/fetchClient.ts"
import { toast } from "sonner"
import { useSubjects } from "@/context/SubjectContext.tsx"
import { useNavigate } from "react-router-dom"

export function NavSubjects({
  subjects,
}: {
  subjects: {
    _id:string,
    userId:string
    title:string
    isAutoGenerated:boolean
  }[]
}) {
  const { isMobile } = useSidebar()
  const location=useLocation()
  const {fetchSubjects}=useSubjects()
  const navigate=useNavigate()
  const handleDelete = (id: string, title: string) => {
    toast(`Delete "${title}"?`, {
      description: "This action cannot be undone.",
      action: {
        label: "Delete",
        onClick: async () => {
          try {
            await apiFetch(`/subjects/${id}`, {
              method: "DELETE",
            });

            toast.success("Subject deleted");

            // Refresh subjects
            fetchSubjects();

            // If user is currently viewing this subject
            if (location.pathname === `/dashboard/${id}`) {
              navigate("/dashboard");
            }
          } catch (err: any) {
            toast.error(
              err.response?.data?.message || "Failed to delete subject",
            );
          }
        },
      },
      cancel: {
        label: "Cancel",
        onClick: () => {},
      },
    });
  };
  return (
    <SidebarGroup className="group-data-[collapsible=icon]:hidden">
      <SidebarGroupLabel>Your Subjects</SidebarGroupLabel>
      <SidebarMenu>
        {subjects.length == 0 && (
          <SidebarMenuItem>
            <span className="text-sm text-muted-foreground px-2 py-1">
              No subjects found
            </span>
          </SidebarMenuItem>
        )}
        {subjects.map((item) => {
          const isActive=location.pathname===`/dashboard/${item._id}`
          return (
            <SidebarMenuItem key={item._id}>
              <SidebarMenuButton
                asChild
                isActive={isActive}
                /* Replaced bg-primary with bg-accent (the standard hover background) */
                className="data-[active=true]:bg-accent data-[active=true]:text-accent-foreground"
              >
                <Link to={`/dashboard/${item._id}`}>
                  <span>{item.title}</span>
                </Link>
              </SidebarMenuButton>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <SidebarMenuAction showOnHover>
                    <MoreHorizontal />
                    <span className="sr-only">More</span>
                  </SidebarMenuAction>
                </DropdownMenuTrigger>
                <DropdownMenuContent
                  className="w-48"
                  side={isMobile ? "bottom" : "right"}
                  align={isMobile ? "end" : "start"}
                >
                  <DropdownMenuItem asChild>
                    <Link to={`/dashboard/${item._id}`}>
                      <Folder className="text-muted-foreground" />
                      <span>View Subject</span>
                    </Link>
                  </DropdownMenuItem>
                  {/* <DropdownMenuItem>
                    <Share className="text-muted-foreground" />
                    <span>Share Project</span>
                  </DropdownMenuItem> */}
                  <DropdownMenuSeparator />
                  <DropdownMenuItem
                    className="text-red-500"
                    onClick={() => handleDelete(item._id,item.title)}
                  >
                    <Trash2 />
                    <span>Delete Subject</span>
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </SidebarMenuItem>
          );
      })}
      </SidebarMenu>
    </SidebarGroup>
  );
}
