import { Worker } from "bullmq";
import connection from "../../config/redis.js";
import Note from "../../models/note.model.js";
import Subject from "../../models/subject.model.js";
import User from "../../models/user.model.js";
import { analyzeLectureImage } from "../../services/ai.service.js";
import parseAIResponse from "../../utils/parseAIResponse.js";
import apiError from "../../utils/apiError.js";

const downloadImageAsBuffer=async(url:string)=>{
    const response=await fetch(url)
    if(!response.ok){
        throw new apiError(500,"Failed to fetch image")
    }
    const arrayBuffer=await response.arrayBuffer()
    return Buffer.from(arrayBuffer)
}

export const noteWorker= new Worker("note-processing",async (job)=>{
    const {noteId,imageUrl}=job.data
    const note=await Note.findById(noteId)
    if(!note){
        throw new apiError(404,"Note not found")
    }
    try {
        const imageBuffer=await downloadImageAsBuffer(imageUrl)
        const aiRaw=await analyzeLectureImage(Buffer.from(""),"image/png")
        const aiData=parseAIResponse(aiRaw)

        const normalizedSubject=aiData.Subject.trim().toLowerCase()
          let subject = await Subject.findOne({
            userId: note.userId,
            title: {
                $regex:new RegExp(
                    `^${normalizedSubject}$`,"i"
                )
            },
          })
          if(!subject){
            subject=await Subject.create({
                userId:note.userId,
                title:normalizedSubject,
                isAutoGenerated:true
            })
          }
          note.subjectId=subject._id
          note.title=aiData.topic
          note.detectedSubject=aiData.subject
          note.aiContent=aiData.notes
          note.status="completed"
          await note.save()
    } catch (error) {
        note.status="failed"
        await note.save()
    }
},{connection:connection as any})